version: '3.7'
services:

  rabbitmq-bus:
    image: rabbitmq:3.7.17-management
    hostname: rabbitmq-bus
    networks:
      - microservices
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  config:
    image: mip/config-service
    # container_name: config
    networks:
      - microservices
    depends_on:
      - rabbitmq-bus
    ports:
      - 8888:8888

  discovery:
    image: mip/discovery-service
    # container_name: discovery
    networks:
      - microservices
    ports:
      - 8761:8761

  admin:
    image: mip/admin-service
    hostname: admin
    # container_name: admin
    networks:
      - microservices
    ports:
      - 7979:7979

networks:
  microservices:
    external: true
