version: '3.7'
services:

  discovery:
    image: mip/discovery-service
    # container_name: discovery
    networks:
      - microservices
    ports:
      - 8761:8761

networks:
  microservices:
    external: true
