version: '3.7'
services:

  gateway:
    image: mip/gateway-service
    hostname: gateway
    # container_name: gateway
    networks:
      - microservices
    ports:
      - 9090:9090

networks:
  microservices:
    external: true
